### ISSUE TITLE
Chrome issue

### ISSUE THREAD

**Issue by realkdhub** [TgCatUB/catuserbot#316]
plugins that uses chrome (google, screenshot, carbon etc...) Having issue executing command for vps users. Please solve the issue soon

**Comment by luisbandalap** [comment]
Chrome related issues only arise if you update Google Chrome as Chrome Driver does not get updated by doing apt upgrade.

You can solve it by updating your chrome driver to match your **exact** google chrome version.

Another solution is to use Debian instead of Ubuntu and install Chromium (this allows you to update all vps packages)

sudo apt install chromium chromium-driver chromium-sandbox

Then set chrome variables as this:

CHROME_BIN="/usr/bin/chromium"
CHROME_DRIVER="/usr/bin/chromedriver"
